# Generated by Django 3.2.23 on 2023-12-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activiteit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('begintijd', models.TimeField()),
                ('eindtijd', models.TimeField()),
                ('omschrijving', models.TextField()),
                ('kosten', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Activiteiten',
            },
        ),
    ]
